BG_GRAY = "#ABB2B9"
BG_COLOR = "#17202A"
TEXT_COLOR = "#EAECEE"

FONT = "Helvetica 14"
FONT_BOLD = "Helvetica 13 bold"
# CODES:
SEND = 200
LOGIN = 201
UPLOAD_MSG_AT_LOGIN = 202
GET_USER_INFO=203
LAST_MSGS=204

IP = "127.0.0.1"
PORT = 8467


#categories:

RESCUE = "rescue"
RESCUE_FROM_CAR = "rescue_from_car"
CHANGE_TIRE = "change_tire"
RESCUE_FROM_HARSH_CONDITIONS = "rescue_from_harsh_conditions"
RESCUE_FROM_ELEVATOR = "rescue_from_elevator"
CHANGE_OIL_AND_WATER = "change_oil_and_water"
TRANSPORTATION = "transportation"
DELIVERY = "delivery"
DANGER = "danger"
GENERAL = "general"
#make a list of all categories
CATEGORIES=[RESCUE,RESCUE_FROM_CAR,CHANGE_TIRE,RESCUE_FROM_HARSH_CONDITIONS,RESCUE_FROM_ELEVATOR,CHANGE_OIL_AND_WATER,TRANSPORTATION,DELIVERY,DANGER,GENERAL]
