BG_GRAY = "#ABB2B9"
BG_COLOR = "#17202A"
TEXT_COLOR = "#EAECEE"

FONT = "Helvetica 14"
FONT_BOLD = "Helvetica 13 bold"
# CODES:
SEND = 200
LOGIN = 201
UPLOAD_MSG_AT_LOGIN = 202
GET_USER_INFO=203
LAST_MSGS=204

IP = "127.0.0.1"
PORT = 34467


#categories:

CAR_HELP = "Car"
RESCUE_FROM_ELEVATOR = "Elevator"
RESCUE_FROM_HARSH_CONDITIONS = "Rescue"
DANGER = "Danger"
GENERAL = "General"
CATEGORIES=[CAR_HELP,RESCUE_FROM_HARSH_CONDITIONS,RESCUE_FROM_ELEVATOR,DANGER,GENERAL]